// @ts-nocheck
// REPO: https://github.com/vrtmrz/livesync-commonlib  Commit hash: 87dc724
import { type ConfigurationItem, type ObsidianLiveSyncSettings } from "./types.ts";
type ExtractPropertiesByType<T, U> = {
    [K in keyof T as T[K] extends U ? K : never]: T[K] extends U ? K : never;
};
export type FilterStringKeys<T> = keyof ExtractPropertiesByType<T, string | undefined>;
export type FilterBooleanKeys<T> = keyof ExtractPropertiesByType<T, boolean | undefined>;
export type FilterNumberKeys<T> = keyof ExtractPropertiesByType<T, number | undefined>;
import type { FilePath, FilePathWithPrefixLC, FilePathWithPrefix, DocumentID } from "./models/db.type.ts";
export type { FilePath, FilePathWithPrefixLC, FilePathWithPrefix, DocumentID };
/**
 * Self-hosted LiveSync settings pane items.
 */
export type OnDialogSettings = {
    configPassphrase: string;
    preset: "" | "PERIODIC" | "LIVESYNC" | "DISABLE";
    syncMode: "ONEVENTS" | "PERIODIC" | "LIVESYNC";
    dummy: number;
    deviceAndVaultName: string;
};
/**
 * Default settings for the OnDialogSettings.
 * Not used for the common library, but used for the Obsidian plugin.
 */
export declare const OnDialogSettingsDefault: OnDialogSettings;
export declare const AllSettingDefault: {
    configPassphrase: string;
    preset: "" | "PERIODIC" | "LIVESYNC" | "DISABLE";
    syncMode: "ONEVENTS" | "PERIODIC" | "LIVESYNC";
    dummy: number;
    deviceAndVaultName: string;
    liveSync: boolean;
    syncOnSave: boolean;
    syncOnStart: boolean;
    syncOnFileOpen: boolean;
    syncOnEditorSave: boolean;
    keepReplicationActiveInBackground: boolean;
    syncMinimumInterval: number;
    showVerboseLog: boolean;
    lessInformationInLog: boolean;
    showLongerLogInsideEditor: boolean;
    showStatusOnEditor: boolean;
    showStatusOnStatusbar: boolean;
    showOnlyIconsOnEditor: boolean;
    hideFileWarningNotice: boolean;
    networkWarningStyle: "" | "icon" | "hidden";
    displayLanguage: import("./rosetta.ts").I18N_LANGS;
    trashInsteadDelete: boolean;
    doNotDeleteFolder: boolean;
    batchSave: boolean;
    batchSaveMinimumDelay: number;
    batchSaveMaximumDelay: number;
    syncMaxSizeInMB: number;
    useIgnoreFiles: boolean;
    ignoreFiles: string;
    processSizeMismatchedFiles: boolean;
    syncOnlyRegEx: import("./types.ts").CustomRegExpSourceList<"|[]|">;
    syncIgnoreRegEx: import("./types.ts").CustomRegExpSourceList<"|[]|">;
    syncAfterMerge: boolean;
    resolveConflictsByNewerFile: boolean;
    writeDocumentsIfConflicted: boolean;
    disableMarkdownAutoMerge: boolean;
    configPassphraseStore: import("./types.ts").ConfigPassphraseStore;
    encryptedPassphrase: string;
    encryptedCouchDBConnection: string;
    periodicReplication: boolean;
    periodicReplicationInterval: number;
    syncInternalFiles: boolean;
    syncInternalFilesBeforeReplication: boolean;
    syncInternalFilesInterval: number;
    syncInternalFilesIgnorePatterns: import("./types.ts").CustomRegExpSourceList<",">;
    syncInternalFilesTargetPatterns: import("./types.ts").CustomRegExpSourceList<",">;
    watchInternalFileChanges: boolean;
    suppressNotifyHiddenFilesChange: boolean;
    syncInternalFileOverwritePatterns: import("./types.ts").CustomRegExpSourceList<",">;
    usePluginSync: boolean;
    usePluginSettings: boolean;
    showOwnPlugins: boolean;
    autoSweepPlugins: boolean;
    autoSweepPluginsPeriodic: boolean;
    notifyPluginOrSettingUpdated: boolean;
    usePluginSyncV2: boolean;
    usePluginEtc: boolean;
    pluginSyncExtendedSetting: Record<import("./types.ts").PluginSyncSettingEntry["key"], import("./types.ts").PluginSyncSettingEntry>;
    useAdvancedMode: boolean;
    usePowerUserMode: boolean;
    useEdgeCaseMode: boolean;
    notifyThresholdOfRemoteStorageSize: number;
    disableWorkerForGeneratingChunks: boolean;
    processSmallFilesInUIThread: boolean;
    savingDelay: number;
    gcDelay: number;
    skipOlderFilesOnSync: boolean;
    useIndexedDBAdapter: boolean;
    enableDebugTools: boolean;
    writeLogToTheFile: boolean;
    settingSyncFile: string;
    writeCredentialsForSettingSync: boolean;
    notifyAllSettingSyncFile: boolean;
    suspendFileWatching: boolean;
    suspendParseReplicationResult: boolean;
    doNotSuspendOnFetching: boolean;
    maxMTimeForReflectEvents: number;
    versionUpFlash: string;
    settingVersion: number;
    isConfigured?: boolean;
    lastReadUpdates: number;
    doctorProcessedVersion: string;
    remoteConfigurations: Record<string, import("./models/setting.type.ts").RemoteConfiguration>;
    activeConfigurationId: string;
    P2P_ActiveRemoteConfigurationId: string;
    couchDB_URI: string;
    couchDB_USER: string;
    couchDB_PASSWORD: string;
    couchDB_DBNAME: string;
    couchDB_CustomHeaders: string;
    useJWT: boolean;
    jwtAlgorithm: import("./models/auth.type.ts").JWTAlgorithm;
    jwtKey: string;
    jwtKid: string;
    jwtSub: string;
    jwtExpDuration: number;
    useRequestAPI: boolean;
    accessKey: string;
    secretKey: string;
    bucket: string;
    region: string;
    endpoint: string;
    useCustomRequestHandler: boolean;
    bucketCustomHeaders: string;
    bucketPrefix: string;
    forcePathStyle: boolean;
    remoteType: import("./types.ts").RemoteType;
    encrypt: boolean;
    passphrase: string;
    usePathObfuscation: boolean;
    E2EEAlgorithm: import("./types.ts").E2EEAlgorithm;
    hashAlg: import("./types.ts").HashAlgorithm;
    minimumChunkSize: number;
    customChunkSize: number;
    longLineThreshold: number;
    useSegmenter: boolean;
    enableChunkSplitterV2: boolean;
    doNotUseFixedRevisionForChunks: boolean;
    chunkSplitterVersion: import("./types.ts").ChunkSplitterVersion;
    useEden: boolean;
    maxChunksInEden: number;
    maxTotalLengthInEden: number;
    maxAgeInEden: number;
    tweakModified: number | undefined;
    checkIntegrityOnSave: boolean;
    useHistory: boolean;
    disableRequestURI: boolean;
    sendChunksBulk: boolean;
    sendChunksBulkMaxSize: number;
    useDynamicIterationCount: boolean;
    doNotPaceReplication: boolean;
    readChunksOnline: boolean;
    useOnlyLocalChunk: boolean;
    concurrencyOfReadChunksOnline: number;
    minimumIntervalOfReadChunksOnline: number;
    enableCompression: boolean;
    batch_size: number;
    batches_limit: number;
    ignoreVersionCheck: boolean;
    disableCheckingConfigMismatch: boolean;
    autoAcceptCompatibleTweak: boolean | undefined;
    hashCacheMaxCount: number;
    hashCacheMaxAmount: number;
    permitEmptyPassphrase: boolean;
    handleFilenameCaseSensitive: boolean;
    checkConflictOnlyOnOpen: boolean;
    showMergeDialogOnlyOnActive: boolean;
    additionalSuffixOfDatabaseName: string | undefined;
    useTimeouts: boolean;
    deleteMetadataOfDeletedFiles: boolean;
    automaticallyDeleteMetadataOfDeletedFiles: number;
    P2P_AutoAccepting: import("./types.ts").AutoAccepting;
    P2P_AutoSyncPeers: string;
    P2P_AutoWatchPeers: string;
    P2P_SyncOnReplication: string;
    P2P_RebuildFrom: string;
    P2P_AutoAcceptingPeers: string;
    P2P_AutoDenyingPeers: string;
    P2P_IsHeadless?: boolean;
    P2P_Enabled: boolean;
    P2P_relays: string;
    P2P_roomID: string;
    P2P_passphrase: string;
    P2P_AppID: string;
    P2P_AutoStart: boolean;
    P2P_AutoBroadcast: boolean;
    P2P_DevicePeerName?: string;
    P2P_turnServers: string;
    P2P_turnUsername: string;
    P2P_turnCredential: string;
    P2P_useDiagRTC?: boolean;
};
export type AllSettings = ObsidianLiveSyncSettings & OnDialogSettings;
export type AllStringItemKey = FilterStringKeys<AllSettings>;
export type AllNumericItemKey = FilterNumberKeys<AllSettings>;
export type AllBooleanItemKey = FilterBooleanKeys<AllSettings>;
export type AllSettingItemKey = AllStringItemKey | AllNumericItemKey | AllBooleanItemKey;
export type ValueOf<T extends AllSettingItemKey> = T extends AllStringItemKey ? string : T extends AllNumericItemKey ? number : T extends AllBooleanItemKey ? boolean : AllSettings[T];
export declare const SettingInformation: Partial<Record<keyof AllSettings, ConfigurationItem>>;
export declare function getConfig(key: AllSettingItemKey): false | {
    name: string;
    desc?: string;
    placeHolder?: string;
    status?: "BETA" | "ALPHA" | "EXPERIMENTAL";
    obsolete?: boolean;
    level?: import("./types.ts").ConfigLevel;
    isHidden?: boolean;
    isAdvanced?: boolean;
};
export declare function getConfName(key: AllSettingItemKey): string;
