import { DoctorRegulation } from "@/lib/src/common/configForDoc";
import {
    DEFAULT_SETTINGS,
    ChunkAlgorithms,
    AutoAccepting,
    type ObsidianLiveSyncSettings,
} from "@/lib/src/common/types";
export const env = (import.meta as any).env;
export const settingBase = {
    ...DEFAULT_SETTINGS,
    isConfigured: true,
    handleFilenameCaseSensitive: false,
    couchDB_URI: `${env.hostname}`,
    couchDB_DBNAME: `${env.dbname}`,
    couchDB_USER: `${env.username}`,
    couchDB_PASSWORD: `${env.password}`,
    bucket: `${env.bucketName}`,
    region: "us-east-1",
    endpoint: `${env.minioEndpoint}`,
    accessKey: `${env.accessKey}`,
    secretKey: `${env.secretKey}`,
    useCustomRequestHandler: true,
    forcePathStyle: true,
    bucketPrefix: "",
    usePluginSyncV2: true,
    chunkSplitterVersion: ChunkAlgorithms.RabinKarp,
    doctorProcessedVersion: DoctorRegulation.version,
    notifyThresholdOfRemoteStorageSize: 800,
    P2P_AutoAccepting: AutoAccepting.ALL,
    P2P_AutoBroadcast: true,
    P2P_AutoStart: true,
    P2P_Enabled: true,
    P2P_passphrase: "p2psync-test",
    P2P_roomID: "p2psync-test",
    P2P_DevicePeerName: "p2psync-test",
    P2P_relays: "ws://localhost:4000/",
    P2P_AutoAcceptingPeers: "p2p-livesync-web-peer",
    P2P_SyncOnReplication: "p2p-livesync-web-peer",
} as ObsidianLiveSyncSettings;
