<script lang="ts">
    import DialogHeader from "@/lib/src/UI/components/DialogHeader.svelte";
    import Guidance from "@/lib/src/UI/components/Guidance.svelte";
    import Decision from "@/lib/src/UI/components/Decision.svelte";
    import Question from "@/lib/src/UI/components/Question.svelte";
    import Option from "@/lib/src/UI/components/Option.svelte";
    import Options from "@/lib/src/UI/components/Options.svelte";
    import Instruction from "@/lib/src/UI/components/Instruction.svelte";
    import UserDecisions from "@/lib/src/UI/components/UserDecisions.svelte";
    import { $msg as msg, currentLang as lang } from "../../../../lib/src/common/i18n.ts";

    const TYPE_USE_SETUP_URI = "use-setup-uri";
    const TYPE_CONFIGURE_MANUALLY = "configure-manually";
    const TYPE_CANCELLED = "cancelled";
    type ResultType = typeof TYPE_USE_SETUP_URI | typeof TYPE_CONFIGURE_MANUALLY | typeof TYPE_CANCELLED;
    type Props = {
        setResult: (result: ResultType) => void;
    };
    const { setResult }: Props = $props();
    let userType = $state<ResultType>(TYPE_CANCELLED);
    let proceedTitle = $derived.by(() => {
        if (userType === TYPE_USE_SETUP_URI) {
            return msg("Proceed with Setup URI", {}, lang);
        } else if (userType === TYPE_CONFIGURE_MANUALLY) {
            return msg("I know my server details, let me enter them", {}, lang);
        } else {
            return msg("Please select an option to proceed", {}, lang);
        }
    });
    const canProceed = $derived.by(() => {
        return userType === TYPE_USE_SETUP_URI || userType === TYPE_CONFIGURE_MANUALLY;
    });
</script>

<DialogHeader title={msg("Connection Method", {}, lang)} />
<Guidance>{msg("We will now proceed with the server configuration.", {}, lang)}</Guidance>
<Instruction>
    <Question>{msg("How would you like to configure the connection to your server?", {}, lang)}</Question>
    <Options>
        <Option selectedValue={TYPE_USE_SETUP_URI} title={msg("Use a Setup URI (Recommended)", {}, lang)} bind:value={userType}>
            {msg(
                "A Setup URI is a single string of text containing your server address and authentication details. Using a URI, if one was generated by your server installation script, provides a simple and secure configuration.",
                {},
                lang
            )}
        </Option>
        <Option
            selectedValue={TYPE_CONFIGURE_MANUALLY}
            title={msg("Enter the server information manually", {}, lang)}
            bind:value={userType}
        >
            {msg(
                "This is an advanced option for users who do not have a URI or who wish to configure detailed settings.",
                {},
                lang
            )}
        </Option>
    </Options>
</Instruction>
<UserDecisions>
    <Decision title={proceedTitle} important={canProceed} disabled={!canProceed} commit={() => setResult(userType)} />
    <Decision title={msg("Cancel", {}, lang)} commit={() => setResult(TYPE_CANCELLED)} />
</UserDecisions>
