// @ts-nocheck
// REPO: https://github.com/vrtmrz/livesync-commonlib  Commit hash: 87dc724
import type { ConfigService } from "@lib/services/base/ConfigService";
import { ControlService } from "@lib/services/base/ControlService";
import type { KeyValueDBService } from "@lib/services/base/KeyValueDBService";
import { PathService } from "@lib/services/base/PathService";
import type { ServiceContext } from "@lib/services/base/ServiceBase";
import type { SettingService } from "@lib/services/base/SettingService";
import { ServiceHub } from "@lib/services/ServiceHub";
import type { UIService } from "@lib/services/implements/base/UIService";
import { InjectableAPIService } from "./InjectableAPIService";
import { type AppLifecycleServiceBase } from "./InjectableAppLifecycleService";
import { InjectableConflictService } from "./InjectableConflictService";
import { InjectableDatabaseEventService } from "./InjectableDatabaseEventService";
import { InjectableFileProcessingService } from "./InjectableFileProcessingService";
import { InjectableRemoteService } from "./InjectableRemoteService";
import { InjectableReplicationService } from "./InjectableReplicationService";
import { InjectableReplicatorService } from "./InjectableReplicatorService";
import type { InjectableServiceInstances } from "./InjectableServices";
import { InjectableTestService } from "./InjectableTestService";
import { InjectableTweakValueService } from "./InjectableTweakValueService";
import { InjectableVaultService } from "./InjectableVaultService";
import type { DatabaseService } from "@lib/services/base/DatabaseService.ts";
export declare class InjectableServiceHub<T extends ServiceContext = ServiceContext> extends ServiceHub<T> {
    protected readonly _api: InjectableAPIService<T>;
    protected readonly _path: PathService<T>;
    protected readonly _database: DatabaseService<T>;
    protected readonly _databaseEvents: InjectableDatabaseEventService<T>;
    protected readonly _replicator: InjectableReplicatorService<T>;
    protected readonly _fileProcessing: InjectableFileProcessingService<T>;
    protected readonly _replication: InjectableReplicationService<T>;
    protected readonly _remote: InjectableRemoteService<T>;
    protected readonly _conflict: InjectableConflictService<T>;
    protected readonly _appLifecycle: AppLifecycleServiceBase<T>;
    protected readonly _setting: SettingService<T>;
    protected readonly _tweakValue: InjectableTweakValueService<T>;
    protected readonly _vault: InjectableVaultService<T>;
    protected readonly _test: InjectableTestService<T>;
    protected readonly _ui: UIService<T>;
    protected readonly _config: ConfigService<T>;
    protected readonly _keyValueDB: KeyValueDBService<T>;
    protected readonly _control: ControlService<T>;
    get API(): InjectableAPIService<T>;
    get path(): PathService<T>;
    get database(): DatabaseService<T>;
    get databaseEvents(): InjectableDatabaseEventService<T>;
    get replicator(): InjectableReplicatorService<T>;
    get fileProcessing(): InjectableFileProcessingService<T>;
    get replication(): InjectableReplicationService<T>;
    get remote(): InjectableRemoteService<T>;
    get conflict(): InjectableConflictService<T>;
    get appLifecycle(): AppLifecycleServiceBase<T>;
    get setting(): SettingService<T>;
    get tweakValue(): InjectableTweakValueService<T>;
    get vault(): InjectableVaultService<T>;
    get test(): InjectableTestService<T>;
    get control(): ControlService<T>;
    get keyValueDB(): KeyValueDBService<T>;
    get UI(): UIService<T>;
    get config(): ConfigService<T>;
    constructor(context: T, services: InjectableServiceInstances<T> & {
        setting: SettingService<T>;
        appLifecycle: AppLifecycleServiceBase<T>;
        path: PathService<T>;
        API: InjectableAPIService<T>;
        ui: UIService<T>;
        config: ConfigService<T>;
        database: DatabaseService<T>;
        vault: InjectableVaultService<T>;
        keyValueDB: KeyValueDBService<T>;
        replicator: InjectableReplicatorService<T>;
    });
}
