// @ts-nocheck
// REPO: https://github.com/vrtmrz/livesync-commonlib  Commit hash: 87dc724
import type { ObsidianLiveSyncSettings } from "./setting.type";
export declare const TweakValuesShouldMatchedTemplate: Partial<ObsidianLiveSyncSettings>;
type TweakKeys = keyof TweakValues;
export declare const IncompatibleChanges: TweakKeys[];
export declare const CompatibleButLossyChanges: TweakKeys[];
type IncompatibleRecommendationPatterns<T extends TweakKeys> = {
    key: T;
    isRecommendation?: boolean;
} & ({
    from: TweakValues[T];
    to: TweakValues[T];
} | {
    from: TweakValues[T];
} | {
    to: TweakValues[T];
});
export declare const IncompatibleChangesInSpecificPattern: IncompatibleRecommendationPatterns<TweakKeys>[];
export declare const TweakValuesRecommendedTemplate: Partial<ObsidianLiveSyncSettings>;
export declare const TweakValuesDefault: Partial<ObsidianLiveSyncSettings>;
export declare const TweakValuesTemplate: {
    tweakModified: number;
    liveSync?: boolean | undefined;
    syncOnSave?: boolean | undefined;
    syncOnStart?: boolean | undefined;
    syncOnFileOpen?: boolean | undefined;
    syncOnEditorSave?: boolean | undefined;
    keepReplicationActiveInBackground?: boolean | undefined;
    syncMinimumInterval?: number | undefined;
    showVerboseLog?: boolean | undefined;
    lessInformationInLog?: boolean | undefined;
    showLongerLogInsideEditor?: boolean | undefined;
    showStatusOnEditor?: boolean | undefined;
    showStatusOnStatusbar?: boolean | undefined;
    showOnlyIconsOnEditor?: boolean | undefined;
    hideFileWarningNotice?: boolean | undefined;
    networkWarningStyle?: "" | "icon" | "hidden" | undefined;
    displayLanguage?: import("../rosetta").I18N_LANGS | undefined;
    trashInsteadDelete?: boolean | undefined;
    doNotDeleteFolder?: boolean | undefined;
    batchSave?: boolean | undefined;
    batchSaveMinimumDelay?: number | undefined;
    batchSaveMaximumDelay?: number | undefined;
    syncMaxSizeInMB?: number | undefined;
    useIgnoreFiles?: boolean | undefined;
    ignoreFiles?: string | undefined;
    processSizeMismatchedFiles?: boolean | undefined;
    syncOnlyRegEx?: import("./shared.type.util").CustomRegExpSourceList<"|[]|"> | undefined;
    syncIgnoreRegEx?: import("./shared.type.util").CustomRegExpSourceList<"|[]|"> | undefined;
    syncAfterMerge?: boolean | undefined;
    resolveConflictsByNewerFile?: boolean | undefined;
    writeDocumentsIfConflicted?: boolean | undefined;
    disableMarkdownAutoMerge?: boolean | undefined;
    configPassphraseStore?: import("./setting.type").ConfigPassphraseStore | undefined;
    encryptedPassphrase?: string | undefined;
    encryptedCouchDBConnection?: string | undefined;
    periodicReplication?: boolean | undefined;
    periodicReplicationInterval?: number | undefined;
    syncInternalFiles?: boolean | undefined;
    syncInternalFilesBeforeReplication?: boolean | undefined;
    syncInternalFilesInterval?: number | undefined;
    syncInternalFilesIgnorePatterns?: import("./shared.type.util").CustomRegExpSourceList<","> | undefined;
    syncInternalFilesTargetPatterns?: import("./shared.type.util").CustomRegExpSourceList<","> | undefined;
    watchInternalFileChanges?: boolean | undefined;
    suppressNotifyHiddenFilesChange?: boolean | undefined;
    syncInternalFileOverwritePatterns?: import("./shared.type.util").CustomRegExpSourceList<","> | undefined;
    usePluginSync?: boolean | undefined;
    usePluginSettings?: boolean | undefined;
    showOwnPlugins?: boolean | undefined;
    autoSweepPlugins?: boolean | undefined;
    autoSweepPluginsPeriodic?: boolean | undefined;
    notifyPluginOrSettingUpdated?: boolean | undefined;
    deviceAndVaultName?: string | undefined;
    usePluginSyncV2?: boolean | undefined;
    usePluginEtc?: boolean | undefined;
    pluginSyncExtendedSetting?: Record<string, import("./setting.type").PluginSyncSettingEntry> | undefined;
    useAdvancedMode?: boolean | undefined;
    usePowerUserMode?: boolean | undefined;
    useEdgeCaseMode?: boolean | undefined;
    notifyThresholdOfRemoteStorageSize?: number | undefined;
    disableWorkerForGeneratingChunks?: boolean | undefined;
    processSmallFilesInUIThread?: boolean | undefined;
    savingDelay?: number | undefined;
    gcDelay?: number | undefined;
    skipOlderFilesOnSync?: boolean | undefined;
    useIndexedDBAdapter?: boolean | undefined;
    enableDebugTools?: boolean | undefined;
    writeLogToTheFile?: boolean | undefined;
    settingSyncFile?: string | undefined;
    writeCredentialsForSettingSync?: boolean | undefined;
    notifyAllSettingSyncFile?: boolean | undefined;
    suspendFileWatching?: boolean | undefined;
    suspendParseReplicationResult?: boolean | undefined;
    doNotSuspendOnFetching?: boolean | undefined;
    maxMTimeForReflectEvents?: number | undefined;
    versionUpFlash?: string | undefined;
    settingVersion?: number | undefined;
    isConfigured?: boolean;
    lastReadUpdates?: number | undefined;
    doctorProcessedVersion?: string | undefined;
    remoteConfigurations?: Record<string, import("./setting.type").RemoteConfiguration> | undefined;
    activeConfigurationId?: string | undefined;
    P2P_ActiveRemoteConfigurationId?: string | undefined;
    couchDB_URI?: string | undefined;
    couchDB_USER?: string | undefined;
    couchDB_PASSWORD?: string | undefined;
    couchDB_DBNAME?: string | undefined;
    couchDB_CustomHeaders?: string | undefined;
    useJWT?: boolean | undefined;
    jwtAlgorithm?: import("./auth.type").JWTAlgorithm | undefined;
    jwtKey?: string | undefined;
    jwtKid?: string | undefined;
    jwtSub?: string | undefined;
    jwtExpDuration?: number | undefined;
    useRequestAPI?: boolean | undefined;
    accessKey?: string | undefined;
    secretKey?: string | undefined;
    bucket?: string | undefined;
    region?: string | undefined;
    endpoint?: string | undefined;
    useCustomRequestHandler?: boolean | undefined;
    bucketCustomHeaders?: string | undefined;
    bucketPrefix?: string | undefined;
    forcePathStyle?: boolean | undefined;
    remoteType?: import("./setting.type").RemoteType | undefined;
    encrypt?: boolean | undefined;
    passphrase?: string | undefined;
    usePathObfuscation?: boolean | undefined;
    E2EEAlgorithm?: import("./setting.type").E2EEAlgorithm | undefined;
    hashAlg?: import("./setting.type").HashAlgorithm | undefined;
    minimumChunkSize?: number | undefined;
    customChunkSize?: number | undefined;
    longLineThreshold?: number | undefined;
    useSegmenter?: boolean | undefined;
    enableChunkSplitterV2?: boolean | undefined;
    doNotUseFixedRevisionForChunks?: boolean | undefined;
    chunkSplitterVersion?: import("./setting.type").ChunkSplitterVersion | undefined;
    useEden?: boolean | undefined;
    maxChunksInEden?: number | undefined;
    maxTotalLengthInEden?: number | undefined;
    maxAgeInEden?: number | undefined;
    checkIntegrityOnSave?: boolean | undefined;
    useHistory?: boolean | undefined;
    disableRequestURI?: boolean | undefined;
    sendChunksBulk?: boolean | undefined;
    sendChunksBulkMaxSize?: number | undefined;
    useDynamicIterationCount?: boolean | undefined;
    doNotPaceReplication?: boolean | undefined;
    readChunksOnline?: boolean | undefined;
    useOnlyLocalChunk?: boolean | undefined;
    concurrencyOfReadChunksOnline?: number | undefined;
    minimumIntervalOfReadChunksOnline?: number | undefined;
    enableCompression?: boolean | undefined;
    batch_size?: number | undefined;
    batches_limit?: number | undefined;
    ignoreVersionCheck?: boolean | undefined;
    disableCheckingConfigMismatch?: boolean | undefined;
    autoAcceptCompatibleTweak?: boolean | undefined;
    hashCacheMaxCount?: number | undefined;
    hashCacheMaxAmount?: number | undefined;
    permitEmptyPassphrase?: boolean | undefined;
    handleFilenameCaseSensitive?: boolean | undefined;
    checkConflictOnlyOnOpen?: boolean | undefined;
    showMergeDialogOnlyOnActive?: boolean | undefined;
    additionalSuffixOfDatabaseName?: string | undefined;
    useTimeouts?: boolean | undefined;
    deleteMetadataOfDeletedFiles?: boolean | undefined;
    automaticallyDeleteMetadataOfDeletedFiles?: number | undefined;
    P2P_AutoAccepting?: import("./setting.type").AutoAccepting | undefined;
    P2P_AutoSyncPeers?: string | undefined;
    P2P_AutoWatchPeers?: string | undefined;
    P2P_SyncOnReplication?: string | undefined;
    P2P_RebuildFrom?: string | undefined;
    P2P_AutoAcceptingPeers?: string | undefined;
    P2P_AutoDenyingPeers?: string | undefined;
    P2P_IsHeadless?: boolean;
    P2P_Enabled?: boolean | undefined;
    P2P_relays?: string | undefined;
    P2P_roomID?: string | undefined;
    P2P_passphrase?: string | undefined;
    P2P_AppID?: string | undefined;
    P2P_AutoStart?: boolean | undefined;
    P2P_AutoBroadcast?: boolean | undefined;
    P2P_DevicePeerName?: string;
    P2P_turnServers?: string | undefined;
    P2P_turnUsername?: string | undefined;
    P2P_turnCredential?: string | undefined;
    P2P_useDiagRTC?: boolean;
};
export type TweakValues = Partial<typeof TweakValuesTemplate>;
export declare const DEVICE_ID_PREFERRED = "PREFERRED";
export {};
